<a href="https://colab.research.google.com/github/mansii2022/big-data-analytics/blob/main/labeval_mca1_202301034_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#multiply the following matrices and also find covariance between matrices using
#numpy: p=[[1,2],[2,3]] q=[[4,5],[6,7]]



In [16]:
import numpy as np

p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

q = q.reshape((2, 2))

multiply = np.dot(p, q)
print("Multiplication of matrices:")
print(multiply)

Multiplication of matrices:
[[16 19]
 [26 31]]


In [15]:
#covariance
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4,5], [6,7]])
covariance = np.cov(p, q)
print("Covariance between matrices:")
print(covariance)

Covariance between matrices:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
